[package]
name = "iced_tabs"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14.0", features = ["advanced"] }
iced_fonts = { version = "0.3.0", features = ["codicon", "advanced_text"] }

